[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
 solaxis_engine = "2eq1RjrJXK4HkWux3xrLqpb6SS7yHuBeDxnPPLVsu6Yj"

[programs.devnet]
 solaxis_engine = "2eq1RjrJXK4HkWux3xrLqpb6SS7yHuBeDxnPPLVsu6Yj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo 'Tests handled via cargo and vitest'"
