[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solaxis_engine = "CcXRe1NVN8fQ2jKyuNhzqZSsVbc6TuVn9SeShapCpb73"

[programs.devnet]
solaxis_engine = "CcXRe1NVN8fQ2jKyuNhzqZSsVbc6TuVn9SeShapCpb73"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo 'Tests handled via cargo and vitest'"
